### ISSUE TITLE
getaddrinfo EAI_AGAIN www.googleapis.com

### ISSUE THREAD

**Issue by xd003** [iwestlin/gd-utils#210]
i was just cloning a folder from one of my shared drive to another and i got the message mentioned in question title during the copying process , i don't really know what does it imply or mean although i hope it can help you to identify the cause of this error/message

```
Started copying files, total： 6500
19:46:31 | Number of files copied 574 | ongoing 20 | Number of Files Pending 5906 getaddrinfo EAI_AGAIN www.googleapis.com
19:58:36 | Number of files copied 6494 | ongoing 6 | Number of Files Pending 0     
Task Completed，Folder Link：
```

Currently , i have not verified if this message caused gdutils to skip some files , i will edit the this issue once i have confirmed the same

**Comment by iwestlin** [comment]
If you google `getaddrinfo EAI_AGAIN`, you will find it's a common error in nodejs, usually happened in docker or some virtualized environment, caused by too many http requests in same time.

I think you could aviod it by reducing `PARALLEL_LIMIT`
https://github.com/roshanconnor123/gd-utils/blob/db72ab3d37d58678dc6afa2bb38b75bc061a3bbf/config.js#L10

By the way, gd-utils will automaticly retry the request if it encountered an error for 7 times max.
So it will not lose the file for only one error.
However if it does fail to copy some file, it will print the id of the file in console, and you could simply rerun the same command to catch up those missed files.

**Comment by xd003** [comment]
Yes apparently it hasn't caued any file to skip from what i can tell . Thanks for clarifying and the prompt reply . I may now close this issue . Have a great day ahead
